### ISSUE TITLE
Bug Payout

### ISSUE THREAD

**Issue by iitzSamy** [Coffeelot/cw-racingapp#14]
When you create a race either with entry money or money for participation, the money is misallocated and it all goes to the first person to win the race.

Also when you choose the type of payment to enter the race, whatever you choose will be charged in cash

**Comment by Coffeelot** [comment]
> When you create a race either with entry money or money for participation, the money is misallocated and it all goes to the first person to win the race.

There's a lot of print outs for splits if you enable debug. Maybe that can help you debug the issue. 
There's a lot of settings for participation and splits in the config. Make sure to check these.

> Also when you choose the type of payment to enter the race, whatever you choose will be charged in cash

I just tested this and it's charging my bank on QBOX at least. If you're running ESX then you'll probably have to find someone that knows ESX since the bridge might be broken.

**If you want more responsive support please use the Discord.**

**Comment by iitzSamy** [comment]
I use qbcore, I will try to make prints to check the problem 💯

**Comment by Leguedric** [comment]
Same problem here whith ESX

**Comment by Coffeelot** [comment]
Have you checked the config for this? 

Participation amounts are split with Config.ParticipationTrophies and Config.ParticipationAmounts.
Config.ParticipationTrophies is a system that pays of for every race (give than the settings in the config are all fullfilled).
Config.ParticipationAmounts is added ontop of a flat amount that can be set when setting up races (as God tier or automated)

I did notice that the bonuses are not getting notified but that's the only thing I can see. Fixing that.

There's also the case with Config.Splits, which handles how the entry fee pot is paid out.
